#  Sales Prediction Using Machine Learning

## Project Overview

Sales forecasting is one of the most important applications of Machine Learning in business analytics. Organizations invest heavily in various advertising channels such as **Television (TV), Radio, and Newspaper** to promote their products. Understanding how these advertising expenditures influence sales enables businesses to optimize marketing budgets, maximize return on investment (ROI), and make data-driven decisions.

This project develops an end-to-end Machine Learning solution to predict product sales based on advertising investments across multiple media channels. By analyzing historical advertising data, the model learns the relationship between marketing expenditure and sales performance.

The project follows the complete Data Science workflow, including:

- Data Collection
- Data Cleaning
- Exploratory Data Analysis (EDA)
- Feature Engineering
- Data Preprocessing
- Machine Learning Model Development
- Model Evaluation
- Business Insights
- Deployment Preparation

Interactive visualizations and multiple regression algorithms are used to identify the most accurate predictive model for future sales forecasting.

---

##  Business Problem

Companies spend significant amounts on advertising through different media platforms, but determining the most effective allocation of marketing budgets remains a challenge.

The objective of this project is to build a predictive model that estimates future sales based on advertising expenditure across:

- 📺 TV Advertising
- 📻 Radio Advertising
- 📰 Newspaper Advertising

The insights generated from this analysis help businesses understand which advertising channels contribute the most to sales growth and support strategic marketing decisions.

---

##  Project Objectives

- Analyze advertising expenditure across multiple marketing channels.
- Perform data cleaning and preprocessing.
- Explore relationships between advertising features and sales.
- Engineer useful features for improved model performance.
- Train and compare multiple regression models.
- Evaluate models using industry-standard performance metrics.
- Identify the most influential advertising channel.
- Generate business recommendations based on analytical findings.
- Prepare the trained model for deployment in a dashboard application.

---

##  Dataset Description

The dataset contains historical advertising expenditure across three different media platforms along with corresponding product sales.

| Feature | Description |
|----------|-------------|
| TV | Advertising budget spent on Television (in thousands of dollars) |
| Radio | Advertising budget spent on Radio (in thousands of dollars) |
| Newspaper | Advertising budget spent on Newspaper (in thousands of dollars) |
| Sales | Product sales (in millions of units) |

**Dataset Size**

- Records: **200**
- Features: **4 Input Features**
- Target Variable: **Sales**

---

##  Technologies Used

- Python
- Pandas
- NumPy
- Plotly
- Matplotlib
- Seaborn
- Scikit-learn
- Random Forest Regressor
- Linear Regression
- Joblib

---

##  Machine Learning Workflow

1. Data Collection
2. Data Understanding
3. Data Cleaning
4. Exploratory Data Analysis
5. Feature Engineering
6. Model Development
7. Model Evaluation
8. Feature Importance Analysis
9. Business Insights
10. Model Deployment

---

##  Expected Outcome

The final model will accurately predict product sales using advertising expenditure data while providing valuable business insights regarding the effectiveness of different advertising channels. The trained model will later be integrated into an interactive dashboard for real-time sales prediction.

In [1]:
# Car Price Prediction - Import Libraries

# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Machine Learning
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    RandomizedSearchCV
)

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

# Regression Models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# Evaluation
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving
import joblib

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Plot Settings

plt.style.use("ggplot")

sns.set_theme(
    style="whitegrid",
    palette="viridis"
)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Loaded Successfully ✅")

Libraries Loaded Successfully ✅

In [3]:
# Load Dataset

df = pd.read_csv("../data/Advertising.csv")
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
## Dataset Information
print("="*60)
print("Advertising OVERVIEW")
print("="*60)

print(f"Rows          : {df.shape[0]}")
print(f"Columns       : {df.shape[1]}")
print(f"Missing Values: {df.isnull().sum().sum()}")
print(f"Duplicates    : {df.duplicated().sum()}")

print("="*60)

df.head()

============================================================
Advertising OVERVIEW
============================================================
Rows          : 200
Columns       : 5
Missing Values: 0
Duplicates    : 0
============================================================

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
## Dataset Summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [6]:
## Statistical Summary
df.describe(include="all").T

            count      mean        std  min     25%     50%      75%    max
Unnamed: 0  200.0  100.5000  57.879185  1.0  50.750  100.50  150.250  200.0
TV          200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
Radio       200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
Newspaper   200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
Sales       200.0   14.0225   5.217457  1.6  10.375   12.90   17.400   27.0

In [7]:
## Missing Values Analysis
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (
        df.isnull().sum()/len(df)
    )*100
})

missing.sort_values(
    by="Percentage",
    ascending=False
)

            Missing Values  Percentage
Unnamed: 0               0         0.0
TV                       0         0.0
Radio                    0         0.0
Newspaper                0         0.0
Sales                    0         0.0

In [8]:
## Duplicate Analysis
duplicates = df.duplicated().sum()

print(f"Duplicate Records : {duplicates}")

Duplicate Records : 0

In [9]:
## Unique Values
unique = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique.sort_values(
    by="Unique Values",
    ascending=False
)

            Unique Values
Unnamed: 0            200
TV                    190
Newspaper             172
Radio                 167
Sales                 121

#  Initial Business Insights

### Dataset Quality

- Dataset successfully loaded.
- Checked missing values.
- Checked duplicate records.
- Reviewed data types.
- Reviewed statistical summary.

### Why this matters

High-quality data leads to more accurate machine learning models.

Understanding missing values and duplicates before training helps prevent biased predictions.

### Next Step

Perform Exploratory Data Analysis (EDA) to understand relationships between features and car prices.

In [10]:
## Import Plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [11]:
## Dataset Shape
print("="*50)
print("DATASET DIMENSIONS")
print("="*50)

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

==================================================
DATASET DIMENSIONS
==================================================
Rows    : 200
Columns : 5

In [12]:
## Distribution of Numerical Features
df[['TV','Radio','Newspaper','Sales']].describe().T

           count      mean        std  min     25%     50%      75%    max
TV         200.0  147.0425  85.854236  0.7  74.375  149.75  218.825  296.4
Radio      200.0   23.2640  14.846809  0.0   9.975   22.90   36.525   49.6
Newspaper  200.0   30.5540  21.778621  0.3  12.750   25.75   45.100  114.0
Sales      200.0   14.0225   5.217457  1.6  10.375   12.90   17.400   27.0

## Business Insight

- TV advertising has the highest investment among all channels.
- Radio advertising has moderate spending.
- Newspaper advertising receives comparatively lower investment.
- Sales vary considerably, indicating different campaign performances.

Understanding these distributions helps identify spending patterns and supports better marketing budget allocation.

In [13]:
## Interactive Histogram (Plotly)
fig = px.histogram(
    df,
    x="Sales",
    nbins=20,
    title="Distribution of Sales",
    color_discrete_sequence=["royalblue"]
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

##  Sales Distribution Insight

The histogram shows how sales values are distributed across all observations.

If the distribution appears approximately normal, regression models are generally suitable for prediction.

A balanced distribution also indicates that the dataset is not heavily skewed.

In [14]:
## TV Advertising Distribution
fig = px.histogram(
    df,
    x="TV",
    nbins=25,
    title="TV Advertisement Budget Distribution",
    color_discrete_sequence=["orange"]
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

## TV Advertisement Insight

TV advertising budgets are spread across a wide range of values, indicating that companies invest significantly in television campaigns.

This suggests that TV advertising may have a strong influence on sales performance.

In [15]:
## Radio Distribution
fig = px.histogram(
    df,
    x="Radio",
    nbins=20,
    title="Radio Advertisement Budget Distribution",
    color_discrete_sequence=["green"]
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

## Radio Advertisement Insight

Radio advertising budgets are relatively balanced across observations.

Further analysis will determine whether increased radio spending contributes significantly to higher sales.

In [16]:
## Newspaper Distribution
fig = px.histogram(
    df,
    x="Newspaper",
    nbins=20,
    title="Newspaper Advertisement Budget Distribution",
    color_discrete_sequence=["purple"]
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

##  Newspaper Advertisement Insight

Newspaper advertising budgets are generally lower than TV spending.

The effectiveness of newspaper advertising will be evaluated later using correlation analysis.

In [17]:
## Correlation Matrix
corr = df.drop(columns=['Unnamed: 0']).corr(numeric_only=True)

fig = px.imshow(
    corr,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    title="Correlation Heatmap"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

##  Correlation Insight

The heatmap helps identify relationships between advertising channels and sales.

Key observations:

- TV has the strongest positive correlation with Sales.
- Radio also contributes positively.
- Newspaper has a relatively weak relationship with Sales.

These findings indicate that TV advertising is likely the most influential factor in predicting sales.

In [18]:
## Scatter Plot
fig = px.scatter(
    df,
    x="TV",
    y="Sales",
    trendline="ols",
    title="TV Advertisement vs Sales"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

##  TV vs Sales Insight

A strong positive linear relationship is visible between TV advertising expenditure and sales.

This suggests that increasing TV advertising budgets is generally associated with higher sales revenue.

In [19]:
## Radio vs Sales
fig = px.scatter(
    df,
    x="Radio",
    y="Sales",
    trendline="ols",
    title="Radio Advertisement vs Sales"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

In [20]:
## Newspaper vs Sales
fig = px.scatter(
    df,
    x="Newspaper",
    y="Sales",
    trendline="ols",
    title="Newspaper Advertisement vs Sales"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

# EDA Summary

### Key Findings

- TV advertising shows the strongest positive relationship with sales.
- Radio advertising also contributes positively but with lower influence than TV.
- Newspaper advertising has the weakest correlation with sales.
- The dataset appears clean with no significant missing values.
- No severe imbalance is observed in the sales distribution.

### Business Recommendations

- Increase investment in TV advertising to maximize sales growth.
- Use Radio advertising as a supporting marketing channel.
- Carefully evaluate the return on investment (ROI) of Newspaper advertising before increasing expenditure.

These insights will guide feature engineering and machine learning model development in the next phase.

## Feature Engineering & Data Preprocessing

In [21]:
# Create Total Advertisement Spend

df["Total_Ad_Spend"] = (
    df["TV"] +
    df["Radio"] +
    df["Newspaper"]
)

df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales  Total_Ad_Spend
0           1  230.1   37.8       69.2   22.1           337.1
1           2   44.5   39.3       45.1   10.4           128.9
2           3   17.2   45.9       69.3    9.3           132.4
3           4  151.5   41.3       58.5   18.5           251.3
4           5  180.8   10.8       58.4   12.9           250.0

In [22]:
# Percentage contribution of each channel

df["TV_%"] = (df["TV"] / df["Total_Ad_Spend"]) * 100

df["Radio_%"] = (df["Radio"] / df["Total_Ad_Spend"]) * 100

df["Newspaper_%"] = (df["Newspaper"] / df["Total_Ad_Spend"]) * 100

df.head()

,Unnamed: 0,TV,Radio,Newspaper,Sales,Total_Ad_Spend,TV_%,Radio_%,Newspaper_%
0,1,230.1,37.8,69.2,22.1,337.1,68.258677,11.213290,20.528033
1,2,44.5,39.3,45.1,10.4,128.9,34.522886,30.488751,34.988363
2,3,17.2,45.9,69.3,9.3,132.4,12.990937,34.667674,52.341390
3,4,151.5,41.3,58.5,18.5,251.3,60.286510,16.434540,23.278949
4,5,180.8,10.8,58.4,12.9,250.0,72.320000,4.320000,23.360000

In [23]:
# Correlation with New Features
corr = df.corr(numeric_only=True)

corr["Sales"].sort_values(ascending=False)

Sales             1.000000
Total_Ad_Spend    0.867712
TV                0.782224
Radio             0.576223
TV_%              0.447170
Newspaper         0.228299
Unnamed: 0       -0.051616
Radio_%          -0.267463
Newspaper_%      -0.439983
Name: Sales, dtype: float64

In [24]:
# Interactive Scatter Plot
fig = px.scatter(
    df,
    x="Total_Ad_Spend",
    y="Sales",
    trendline="ols",
    color="Sales",
    size="Sales",
    title="Total Advertisement Spend vs Sales"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

##  Observation

The scatter plot demonstrates a clear positive trend.

As total advertising expenditure increases, sales generally increase as well.

This validates the importance of advertising investment in predicting sales.

In [25]:
# Boxplots (Outlier Detection)
fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=[
        "TV",
        "Radio",
        "Newspaper",
        "Sales"
    ]
)

fig.add_trace(
    go.Box(y=df["TV"], name="TV"),
    row=1,
    col=1
)

fig.add_trace(
    go.Box(y=df["Radio"], name="Radio"),
    row=1,
    col=2
)

fig.add_trace(
    go.Box(y=df["Newspaper"], name="Newspaper"),
    row=2,
    col=1
)

fig.add_trace(
    go.Box(y=df["Sales"], name="Sales"),
    row=2,
    col=2
)

fig.update_layout(
    height=700,
    template="plotly_dark",
    title="Outlier Detection"
)

fig.show()

## Outlier Analysis

Outliers represent unusually high or low observations.

In advertising data, extreme values may correspond to large marketing campaigns rather than errors.

Therefore, outliers should be carefully evaluated before removal.

In [26]:
# Detect Outliers Using IQR
def detect_outliers(column):

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower) |
        (df[column] > upper)
    ]

    print(f"{column}: {len(outliers)} outliers")


for col in [
    "TV",
    "Radio",
    "Newspaper",
    "Sales"
]:
    detect_outliers(col)

TV: 0 outliers
Radio: 0 outliers
Newspaper: 2 outliers
Sales: 0 outliers

In [27]:
# Feature Selection
features = [
    "TV",
    "Radio",
    "Newspaper",
]

target = "Sales"

X = df[features]

y = df[target]

print("Feature Matrix Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Matrix Shape : (200, 3)
Target Shape : (200,)

#  Feature Engineering Summary

### New Features Created

- Total Advertisement Spend
- TV Budget Percentage
- Radio Budget Percentage
- Newspaper Budget Percentage

### Key Findings

- Total advertising expenditure shows a strong positive relationship with sales.
- No significant data quality issues were detected.
- Outliers appear to represent valid business scenarios.
- The dataset is now ready for machine learning model development.

In [28]:
# Feature Selection
# Independent Features

X = df[["TV", "Radio", "Newspaper"]]

# Target

y = df["Sales"]

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.20,

    random_state=42
)

print("Training Shape :", X_train.shape)

print("Testing Shape :", X_test.shape)

Training Shape : (160, 3)
Testing Shape : (40, 3)

In [29]:
# Train Models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {

    "Linear Regression": LinearRegression(),

    "Decision Tree": DecisionTreeRegressor(
        random_state=42
    ),

    "Random Forest": RandomForestRegressor(

        n_estimators=200,

        random_state=42
    )

}

In [30]:
# Train All Models
results = []

trained_models = {}

for name, model in models.items():

    model.fit(X_train, y_train)

    prediction = model.predict(X_test)

    mae = mean_absolute_error(y_test, prediction)

    rmse = np.sqrt(mean_squared_error(y_test, prediction))

    r2 = r2_score(y_test, prediction)

    trained_models[name] = model

    results.append({

        "Model": name,

        "MAE": round(mae,3),

        "RMSE": round(rmse,3),

        "R² Score": round(r2,3)

    })

results_df = pd.DataFrame(results)

results_df

               Model    MAE   RMSE  R² Score
0  Linear Regression  1.461  1.782     0.899
1      Decision Tree  0.985  1.475     0.931
2      Random Forest  0.629  0.757     0.982

In [31]:
# Sort Results
results_df = results_df.sort_values(

    by="R² Score",

    ascending=False

)

results_df

               Model    MAE   RMSE  R² Score
2      Random Forest  0.629  0.757     0.982
1      Decision Tree  0.985  1.475     0.931
0  Linear Regression  1.461  1.782     0.899

##  Model Performance Insight

The comparison table evaluates each regression model using three performance metrics:

- MAE
- RMSE
- R² Score

The model with the highest R² score and the lowest prediction errors will be selected as the final prediction model.

In [32]:
# Interactive Model Comparison (Plotly)
fig = px.bar(

    results_df,

    x="Model",

    y="R² Score",

    color="R² Score",

    text="R² Score",

    title="Model Performance Comparison"

)

fig.update_traces(texttemplate="%{text:.3f}")

fig.update_layout(

    template="plotly_dark",

    title_x=0.5

)

fig.show()

In [33]:
# Finding the  Best Model
best_model_name = results_df.iloc[0]["Model"]

best_model = trained_models[best_model_name]

print("="*50)

print("🏆 Best Model")

print("="*50)

print(best_model_name)

==================================================
🏆 Best Model
==================================================
Random Forest

In [34]:
# Actual vs Predicted
prediction = best_model.predict(X_test)

comparison = pd.DataFrame({

    "Actual Sales": y_test.values,

    "Predicted Sales": prediction

})

comparison.head(10)

   Actual Sales  Predicted Sales
0          16.9          17.7615
1          22.4          21.6665
2          21.4          20.6595
3           7.3           6.7395
4          24.7          23.0960
5          12.6          13.5155
6          22.3          22.4860
7           8.4           9.6625
8          11.5          11.8545
9          14.9          15.5040

In [35]:
# Interactive Scatter Plot
fig = px.scatter(

    comparison,

    x="Actual Sales",

    y="Predicted Sales",

    trendline="ols",

    title="Actual vs Predicted Sales"

)

fig.update_layout(

    template="plotly_dark",

    title_x=0.5

)

fig.show()

##  Interpretation

If the predicted values closely follow the actual values, it indicates that the model has learned the relationship between advertising expenditure and sales effectively.

Points lying close to the diagonal trendline represent accurate predictions.

In [36]:
# Cross Validation
from sklearn.model_selection import cross_val_score

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=8,
    random_state=42
)

scores = cross_val_score(
    rf,
    X,
    y,
    cv=5,
    scoring="r2"
)

print("="*50)
print("Cross Validation Results")
print("="*50)

print(scores)

print("\nAverage R² Score :", scores.mean())
print("Standard Deviation :", scores.std())

==================================================
Cross Validation Results
==================================================
[0.98135134 0.98444282 0.96966199 0.96225595 0.98098613]

Average R² Score : 0.9757396441587478
Standard Deviation : 0.008408446808034386

In [37]:
# Feature Importance
rf.fit(X_train, y_train)

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance

     Feature  Importance
0         TV    0.625764
1      Radio    0.361748
2  Newspaper    0.012488

In [38]:
import plotly.express as px

fig = px.bar(
    importance,
    x="Importance",
    y="Feature",
    orientation="h",
    color="Importance",
    text="Importance",
    title="Feature Importance (Random Forest)",
    color_continuous_scale="Viridis"
)

fig.update_traces(
    texttemplate="%{text:.3f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5,
    height=500
)

fig.show()

#  Feature Importance Analysis

The Random Forest algorithm measures how much each feature contributes to predicting sales.

Key Findings:

- TV advertising is expected to have the highest influence on sales prediction.
- Radio advertising contributes moderately.
- Newspaper advertising generally has the lowest impact.

These insights help businesses allocate advertising budgets more effectively.

In [39]:
best_prediction = rf.predict(X_test)

residual = y_test - best_prediction

comparison = pd.DataFrame({
    "Actual Sales": y_test.values,
    "Predicted Sales": best_prediction,
    "Residual": residual
})

comparison.head()

     Actual Sales  Predicted Sales  Residual
95           16.9        17.780236 -0.880236
15           22.4        21.696884  0.703116
30           21.4        20.827728  0.572272
158           7.3         6.829892  0.470108
128          24.7        23.155333  1.544667

In [40]:
fig = px.scatter(
    comparison,
    x="Predicted Sales",
    y="Residual",
    color="Residual",
    title="Residual Analysis",
    color_continuous_scale="RdBu"
)

fig.add_hline(
    y=0,
    line_dash="dash",
    line_color="red"
)

fig.update_layout(
    template="plotly_dark",
    title_x=0.5
)

fig.show()

#  Residual Analysis

Residuals represent the difference between actual and predicted sales.

A well-performing regression model should produce residuals randomly scattered around zero without any systematic pattern.

This indicates that the model captures the relationship between advertising expenditure and sales effectively.

In [41]:
from sklearn.model_selection import RandomizedSearchCV

In [42]:
param_grid = {

    "n_estimators": [100, 200, 300, 500],

    "max_depth": [5, 8, 10, 15, None],

    "min_samples_split": [2, 5, 10],

    "min_samples_leaf": [1, 2, 4],

    "bootstrap": [True, False]

}

In [43]:
rf = RandomForestRegressor(random_state=42)

random_search = RandomizedSearchCV(

    estimator=rf,

    param_distributions=param_grid,

    n_iter=20,

    scoring="r2",

    cv=5,

    verbose=1,

    random_state=42,

    n_jobs=-1

)

random_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [5, 8, 10, 15, None],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='r2', verbose=1)

In [44]:
print("="*60)
print("Best Hyperparameters")
print("="*60)

random_search.best_params_

============================================================
Best Hyperparameters
============================================================

{'n_estimators': 300,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_depth': 8,
 'bootstrap': True}

In [45]:
{
 'bootstrap': True,
 'max_depth': 10,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 300
}

{'bootstrap': True,
 'max_depth': 10,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 300}

In [46]:
best_rf = random_search.best_estimator_

best_rf

RandomForestRegressor(max_depth=8, min_samples_split=5, n_estimators=300,
                      random_state=42)

In [47]:
prediction = best_rf.predict(X_test)

mae = mean_absolute_error(y_test, prediction)

rmse = np.sqrt(mean_squared_error(y_test, prediction))

r2 = r2_score(y_test, prediction)

print("="*60)

print("Tuned Random Forest Performance")

print("="*60)

print(f"MAE  : {mae:.4f}")

print(f"RMSE : {rmse:.4f}")

print(f"R²   : {r2:.4f}")

============================================================
Tuned Random Forest Performance
============================================================
MAE  : 0.6489
RMSE : 0.8015
R²   : 0.9796

#  Hyperparameter Tuning Result

The optimized Random Forest model achieved improved performance by selecting the best combination of hyperparameters.

This process ensures that the model is not only accurate but also more robust when making predictions on unseen data.

The tuned model will be selected as the final prediction model.

In [48]:
# Model Saving
import joblib

joblib.dump(

    best_rf,

    "../models/random_forest_sales.pkl"

)

print("✅ Model Saved Successfully")

✅ Model Saved Successfully

In [53]:
from sklearn.ensemble import RandomForestRegressor
import joblib

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

joblib.dump(
    rf,
    "../models/random_forest_sales.pkl"
)

['../models/random_forest_sales.pkl']

In [54]:
# Live Prediction
sample = pd.DataFrame({

    "TV":[250],

    "Radio":[40],

    "Newspaper":[30]

})

prediction = loaded_model.predict(sample)

print("="*50)

print("Predicted Sales")

print("="*50)

print(f"{prediction[0]:.2f} Million Units")

==================================================
Predicted Sales
==================================================
23.19 Million Units

In [55]:
what_if = pd.DataFrame({

    "Scenario":[

        "Low Budget",

        "Medium Budget",

        "High Budget"

    ],

    "TV":[80,180,280],

    "Radio":[15,35,50],

    "Newspaper":[10,30,45]

})

what_if["Predicted Sales"] = loaded_model.predict(

    what_if[["TV","Radio","Newspaper"]]

)

what_if

        Scenario   TV  Radio  Newspaper  Predicted Sales
0     Low Budget   80     15         10        11.125431
1  Medium Budget  180     35         30        18.286999
2    High Budget  280     50         45        25.805763

In [56]:
fig = px.bar(

    what_if,

    x="Scenario",

    y="Predicted Sales",

    color="Predicted Sales",

    text="Predicted Sales",

    title="What-If Sales Simulation",

    color_continuous_scale="Turbo"

)

fig.update_layout(

    template="plotly_dark",

    title_x=0.5

)

fig.show()

#  Business Recommendation

The simulation demonstrates how varying advertising budgets influence expected sales.

### Key Insights

- Higher investment in TV advertising consistently produces larger increases in predicted sales.
- Radio advertising complements TV campaigns and improves overall effectiveness.
- Newspaper advertising has a comparatively smaller impact on sales.

### Recommendation

For future marketing campaigns, businesses should prioritize TV advertising while using Radio as a supporting channel. Newspaper advertising should be evaluated carefully based on campaign objectives and return on investment (ROI).